
# NOTE: Note Implemented!!
commands:
  # The name of the pvp command
  # Default: pvp
  pvp-command-label: pvp
  # The name of the duel command
  # Default: duel
  duel-command-label: duel

mob-protection:
  # Enable or disable pet protection. Protects a player's pets from
  # other players if they can't engage in PvP.
  # Default: true
  pet-protection: true
  # List of all pets protected.
  # Default: Wolf, Cat, Parrot
  # Supported: Wolf, Cat, Parrot, Horse, Donkey, Mule, Skeleton Horse
  protected-pets:
    - Wolf
    - Cat
    - Parrot

  # Enabled or disable mount protection. Protects the mob a player
  # is riding if they can't engage in PvP.
  # Default: true
  mount-protection: true
  # List of all mounts protected.
  # Default: Horse, Donkey, Skeleton Horse, Mule, Skeleton Horse, Pig, Strider
  # Supported: Horse, Donkey, Skeleton Horse, Mule, Skeleton Horse, Pig, Strider
  protected-mounts:
    - Horse
    - Donkey
    - Skeleton Horse
    - Mule
    - Llama
    - Pig
    - Strider

# NOTE: Not Implemented
# Set the different messages
# As of right now, does not support
# placeholder api
messages:
  your-pvp-disabled: "&eYour PvP is disabled"
  your-pvp-updated: "&eYour PvP has been set to: &b{status}"
  their-pvp-disabled: "&e{player}'s PvP is disabled"
  player-in-duel: "&eIF YOU SEE THIS SCREAM AT THE ADMINS"
  pvp-status: "&eYour PvP is set to: &b{status}"
  pvp-global-status: "Global override is &b{status}"
  pvp-override-status: "Global override will override PvP with: &b{status}"

# DO NOT TOUCH
# Marks the version of this config. The plugin will complain if it's incorrect
config-version: 3
