name: "CustomizableCombat"
version: "2.0"
main: searous.customizableCombat.main.CustomizableCombat
api-version: "1.17"
commands:
  duel:
    description:  ""
    usage: /duel <target> [bet] [<item>] [count]
permissions:
  customizable-combat.pvp:
    description: Gives access to /pvp <on/off>. Defaults to true
    default: true
  customizable-combat.pvp.set:
    description: Gives access to /pvp set <player> <on/off>
    default: op
  customizable-combat.pvp.override.set:
    description: Allows access to setting the override settings
    default: op
  customizable-combat.pvp.override.check:
    description: Allows access to setting the override settings
    default: op
  customizable-combat.pvp.check:
    description: Gives acces to /pvp check <player>. Defaults to true
    default: true
  customizable-combat.duel:
    description:  Gives access to the /duel command
    default: true
softdepend:
  - PlaceholderAPI